version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: trading_app_db
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: gunicorn trading_app.asgi:application --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A trading_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - db
      - redis